spring:
  application:
    name: matchs service
  datasource:
    url: jdbc:postgresql://localhost:5432/pmatchsDB
    username: postgres
    password: achraf
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  cloud:
    client:
      discovery:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    app:
      name: match microservice
      description: match microservice
      version: 1.0.0
server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  # URL du serveur Eureka
